theme: hugo-ivy
baseurl: https://collabin.netlify.com/
languageCode: zh-tw
title: 協作閣
ignoreFiles:
  - \.Rmd$
  - _files$
  - _cache$
hasCJKLanguage: true
enableEmoji: true
rssLimit: 100
footnotereturnlinkcontents: ↩
menu:
  main:
    - name: "Home\U0001F3E0"
      url: /
      weight: 1
    - name: "發表\U0001F4C2"
      url: /info/submit/
      weight: 2
    - name: About
      url: /info/about/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: ' '
      weight: 10
    - name: "作者\U0001F465"
      url: /info/authors/
      weight: 15
    - name: Yongfu Liao
      url: /yongfu/
      weight: 100   # author weights are always 100
params:
  customJS:
    - js/fix-toc.js
    - js/center-img.js
    - js/right-quote.js
    - js/no-highlight.js
    - js/fix-footnote.js
    - js/math-code.js
    - js/external-link.js
    - js/alt-title.js
  description: 開源協作部落格
  disqusURL: 'http://corbloggers.disqus.com'
  footer: '© [協作閣](/) 2019'
  githubContentURL: 'https://github.com/rbind/yihui/edit/master/content/'
  highlightjsCDN: //cdn.bootcss.com
  highlightjsLang:
    - r
    - yaml
    - toml
    - tex
    - python
    - bash
    - javascript
    - css
    - html
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  twitterImage: /images/logo.png

